# Промисы
---

>Асинхронность - не совпадение с чем-либо во времени; неодномоментность, неодновременность, несинхронность.

>Промис представляет собой объект, в который параметром передается функция, внутри которой нужно размещать наш асинхронный код.

Синтаксис:
```js
let promise = new Promise(function() { 
	// асинхронный код 
});

promise.then(function() { 
	// выполнится при завершении асинхронного кода 
});
```

Метод `then` передаем в него функцию с кодом, который должен быть выполнен по завершении асинхронного кода.
`then` всегда возвращает новый промис, то его удобно использовать для построения последовательностей асинхронных операций.

---

Первый параметр `resolve` - явно указываем промису, что асинхронный код завершился. 

```js
let promise = new Promise(function(resolve) { // указываем параметр
	setTimeout(function() { 
		let result = [1, 2, 3, 4, 5]; 
		resolve(result); // завершаем промис и (передаем результат)
	}, 3000); 
});

promise.then(function(result) { 
	console.log(result); // выведет массив с результатом 
});
```

---

Второй параметр `reject` - если возникла исключительная ситуация.

```js
let promise = new Promise(function(resolve, reject) { 
	setTimeout(function() { 
		let isError = false; 
		if (!isError) { 
			resolve([1, 2, 3, 4, 5]); // данные промиса 
		} else { 
			reject('error in promise'); // ваш текст ошибки 
		} 
	}, 3000); 
});

promise.then(function(result) { 
	console.log(result); // выведет результат промиса 
}, function(error) { 
	console.log(error); // выведет текст ошибки 
});
```

---

Использование объекта с ошибкой.

Более принято в функцию `reject` передавать не строку с ошибкой, а объект с ошибкой:
```js
let promise = new Promise(function(resolve, reject) { 
	setTimeout(function() { 
		reject(new Error('error in promise')); // объект с ошибкой 
	}, 3000); 
});
```

Можно также выбрасывать объекты с ошибками с помощью `throw` - это будет эквивалентно передаче их в `reject`:
```js
let promise = new Promise(function(resolve, reject) { 
	setTimeout(function() { 
		throw new Error('error in promise'); // эквивалентно reject 
	}, 3000); 
});
```

---

Только обработка ошибок.

В `then` можно указать только функцию-обработчик исключительной ситуации, передав вместо первого параметра `null`:
```js
promise.then( 
	null, 
	function(error) { 
		console.log(error); 
	} 
);
```

В таком случае удобно воспользоваться сокращенным синтаксисом через метод `catch`:
```js
promise.catch( 
	function(error) { 
		console.log(error); 
	} 
);
```

>Метод `catch` полностью эквивалентен методу `then`, у которого первый параметр `null`.

----

Цепочки промисов:
```js
let promise = new Promise(function(resolve, reject) { 
	setTimeout(function() { 
		resolve('string'); 
	}, 3000); 
});

promise.then( 
	function(result) { 
		return result + '1'; 
	} 
).then( 
	function(result) { 
		return result + '2'; 
	} 
).then( 
	function(result) { 
		return result + '3'; 
	} 
).then( 
	function(result) { 
		console.log(result); // выведет 'string123' 
	} 
);
```

>Функции цепочки могут также возвращать промисы.

----

Исключительные ситуации.

Пусть по каким-то причинам наш промис завершится с ошибкой:
```js
let promise = new Promise(function(resolve, reject) { 
	setTimeout(function() { 
		reject('error'); 
	}, 3000); 
});
```

>В этом случае выполнение кода сразу перейдет к тому `then`, в котором есть функция-обработчик ошибки, либо к первому `catch`, смотря что встретится раньше.

```js
promise.then(
	function(result) {
		return result + '1';
	}
).then(
	function(result) {
		return result + '2';
	},
	function(error) {
		// выполнение сразу перейдет сюда
	}
).then(
	function(result) {
		console.log(result);
	}
);
```

или так:
```js
promise.then(
	function(result) {
		return result + '1';
	}
).then(
	function(result) {
		return result + '2';
	}
).catch(
	function(error) {
		// выполнение сразу перейдет сюда
	}
).then(
	function(result) {
		console.log(result);
	}
);
```

>`catch` нужен именно для диагностики ошибки: она решаема или нет. Если ошибка решаема, то `catch` должен передать ее решение следующему за собой `then`. А если не решаема (или данный `catch` просто не знает как ее решить), то мы должны или ничего не вернуть или бросить исключение.

---

Работа с массивами промисов.

- Метод `Promise.all` позволяет выполнить код по окончанию всех промисов, переданных ему в виде массива.
- Метод `Promise.race` дожидается загрузки первого промиса из массива, отбрасывая остальные.

```js
let promises = [
	new Promise(resolve => setTimeout(() => resolve(1), 1000)),
	new Promise(resolve => setTimeout(() => resolve(2), 2000)),
	new Promise(resolve => setTimeout(() => resolve(3), 3000)),
];

Promise.all(promises).then(function(res) {
	console.log(res); // выведет [1, 2, 3] - результаты всех промисов
});

Promise.race(promises).then(function(res) {
	console.log(res); // выведет 1 - результат первого выполнившегося промиса
});
```

---

Создание сработавших промисов.

- Метод `Promise.resolve` создает выполненный успешно промис.
- Метод `Promise.reject` создает отклоненный промис.

Пусть теперь мы решили, что для переданного нуля мы должны вернуть ноль, а для чисел меньше нуля - исключение.
```js
function func(num) {
	if (num > 0) {
		return new Promise(function(resolve) {
			setTimeout(function() {
				resolve(num * num);
			}, 3000);
		});
	} else if (num === 0) {
		return Promise.resolve(0); // возвращаем промис, а не число
	} else {
		return Promise.reject('incorrect number'); // вернем отклоненный промис
	}
}
```

----

Обьявляем нашу функцию ассинхронной `async`.
Ждем выполнения нашего промиса с помощью команды `await`.
В исключительных ситуациях применяем `try-catch`.
```js
async function func() {
	try {
		let res = await getSmth(2);
		console.log(res);
	} catch (err) {
		console.log(err);
	}
}

func();
```